import { useState } from 'react';
import FlightCard from './FlightCard';
import InfoSectionCard from './InfoSectionCard';
import formatDate from '../utils/FormatDate';
import WeatherCard from './WeatherCard';
import { Sparkles, Info } from 'lucide-react';
import InfoTooltip from '../utils/InfoTooltip';
import currencyFormatter from '../utils/currencyFormatter';
import buildGoogleHotelUrl from '../utils/buildGoogleHotelUrl';
import buildGooglePackagesUrl from '../utils/buildGooglePackagesUrl';