# Generated by Django 6.0.4 on 2026-05-02 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('legal_status', models.TextField(help_text='Marriage equality, anti-discrimination laws, etc.')),
                ('social_vibe', models.TextField(help_text='Local community infrastructure and safety.')),
                ('travel_alerts', models.TextField(blank=True, help_text='Specific risks or censorship.', null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engine.location')),
            ],
        ),
    ]
