# Generated by Django 6.0.4 on 2026-05-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='airport_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='safetyindex',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
