# Generated by Django 6.0.4 on 2026-05-09 13:05

from django.db import migrations, models


def populate_safety_country_fields(apps, schema_editor):
    SafetyIndex = apps.get_model('engine', 'SafetyIndex')
    for safety in SafetyIndex.objects.select_related('location').all():
        if safety.location_id and not safety.country_name:
            safety.country_name = safety.location.country_name
            safety.save(update_fields=['country_name'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_location_airport_name_alter_safetyindex_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='safetyindex',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='safetyindex',
            name='country_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(
            code=populate_safety_country_fields,
            reverse_code=noop_reverse,
        ),
        migrations.RemoveField(
            model_name='safetyindex',
            name='location',
        ),
        migrations.AlterField(
            model_name='safetyindex',
            name='legal_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='safetyindex',
            name='social_vibe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='safetyindex',
            name='travel_alerts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
