# Generated by Django 6.0.4 on 2026-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_remove_safetyindex_location_location_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='safetyindex',
            name='country_code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='safetyindex',
            name='country_name',
            field=models.CharField(max_length=100),
        ),
    ]
